[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' https: data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval' https: blob:;"

[[redirects]]
  from = "/"
  to   = "/NCEF-Portal-Bundle.html"
  status = 200

[[redirects]]
  from = "/*"
  to   = "/NCEF-Portal-Bundle.html"
  status = 200
